# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210919_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article2articletype',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2articletype',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_types',
        ),
        migrations.AddField(
            model_name='article',
            name='article_types',
            field=models.ForeignKey(default=2017, on_delete=django.db.models.deletion.CASCADE, to='app01.ArticleType'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Article2ArticleType',
        ),
    ]
