# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-23 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_article_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='article',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
